---
apiVersion: apps/v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  hostNetwork: true
  serviceAccountName: kubedoom
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
  containers:
  - image: nginx:1.12
    name: nginx
    ports:
    - containerPort: 5900
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 4Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubedoom
    namespace: kubedoom
